#%RAML 1.0
title: Edge API - Real Time Availability Check
baseUri: https://github.com/folio-org/edge-rtac
version: v2

documentation:
  - title: Edge API - Real Time Availability Check
    content: Edge API to interface with FOLIO for 3rd party discovery services to determine holdings availability

schemas:
  holdings: !include holdings.xsd
  batchHoldings: !include batch-holdings.xsd

/rtac:
  displayName: RTAC Batching
  get:
    description: Batch RTAC for the specified ids
    responses:
      200:
        description: "Success"
        body:
          application/xml:
            type: batchHoldings
    queryParameters:
      instanceIds:
        description: "List of Folio instance identifiers"
        type: string
        pattern: "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}[, ]*)+$"
      fullPeriodicals:
        description: "Flag for including items data"
        type: boolean
      apikey:
        description: "API Key"
        type: string

/rtac/{instanceId}:
  displayName: RTAC
  get:
    description: RTAC for the specified holding id
    responses:
      200:
        description: "Success"
        body:
          application/xml:
            type: holdings
    queryParameters:
      fullPeriodicals:
        description: "Flag for including items data"
        type: boolean
      apikey:
        description: "API Key"
        type: string

/prod/rtac/folioRTAC:
  displayName: RTAC
  get:
    description: <Deprecated> RTAC for the specified holding id
    responses:
      200:
        description: "Success"
        body:
          application/xml:
            type: holdings
    queryParameters:
      mms_id:
        description: "The UUID of a FOLIO instance"
        type: string
        pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
      apikey:
        description: "API Key"
        type: string

/admin/health:
  displayName: Health Check
  get:
    description: Health Check
    responses:
      200:
        description: "Success"
        body:
          text/plain:
